package token

enum class TokenType {
    IDENTIFIER,
    KEYWORD,
    PUNCTUATOR,
    OPERATOR,
    STRINGLITERAL,
    NUMBERLITERAL,
    BOOLEANLITERAL,
    DECLARATOR,
    ASSIGNATION,
    PARENTHESIS,
    DATA_TYPE,
    FUNCTION,
    CONDITIONAL,
    UNKNOWN,
}
